from enum import Enum


class ChainType(Enum):
    HUMAN_HEAVY = 1
    HUMAN_LIGHT = 2
    CHICKEN_HEAVY = 3
    CHICKEN_LIGHT = 4
    RABBIT_HEAVY = 5
    RABBIT_KAPPA = 6
    MOUSE_BALBC_HEAVY = 7
    MOUSE_BALBC_LIGHT = 8
    MOUSE_C57BL6_HEAVY = 9
    MOUSE_C57BL6_LIGHT = 10

    ALPACA_HEAVY = 11

    MOUSE_HEAVY = 12
    MOUSE_LIGHT = 13

    HUMAN_BETA = 14
    HUMAN_ALPHA = 15
    HUMAN_GAMMA = 16
    HUMAN_DELTA = 17

    MOUSE_BETA = 18
    MOUSE_ALPHA = 19
    MOUSE_GAMMA = 20
    MOUSE_DELTA = 21

    RAT_HEAVY = 98
    RAT_LIGHT = 99

    MOUSE_HEAVY_ATC_MOUSE = 100
